[package]
name = "corinth"
version = "0.0.1"
authors = ["dotvirus <33938500+dotvirus@users.noreply.github.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = "0.4"
oysterpack_uid = "0.2.0"

[dependencies.nickel]
version = "*"
